export const ADMIN_MUTATION_KEY = {
  POST_NEW_LEAGUE: 'POST_NEW_LEAGUE',
  PUT_LEAGUE: 'PUT_LEAGUE',
  DELETE_LEAGUE: 'DELETE_LEAGUE',
  POST_TEAM: 'POST_TEAM',
  POST_LOGIN: 'POST_LOGIN',
  PUT_MATCH_INFO: 'PUT_MATCH_INFO',
} as const;
