export const ADMIN_QUERY_KEY = {
  LEAGUE_LIST: 'LEAGUE_LIST',
  LEAGUE_SPORTS: 'LEAGUE_SPORTS',
  SPORTS_LIST: 'SPORTS_LIST',
  TEAM_LIST: 'TEAM_LIST',
  SPORTS_QUARTER: 'SPORTS_QUARTER',
  MATCH_INFO: 'MATCH_INFO',
} as const;
