name: 'Sync Spectator'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

permissions: write-all

jobs:
  sync-fork-repo:
    runs-on: ubuntu-latest
    if: github.repository == 'hufscheer/web'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.HCC_GITHUB_KEY }}
      - name: Commit files
        run: |
          git config user.email "hufscheercheer@gmail.com"
          git config user.name "hufscheer"
          git commit --amend --author="hufscheer <hufscheercheer@gmail.com>" --no-edit
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.HCC_GITHUB_KEY }}
          repository: hufscheer-saas/hufscheer-web
          force: true
          branch: ${{ github.ref }}
